# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 00:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_auto_20160901_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFieldsTest5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserFieldsTest3',
        ),
    ]
